package aeon.modelo.dto;
// Generated 10-10-2018 06:07:14 PM by Hibernate Tools 4.3.1



/**
 * DetalleVenta generated by hbm2java
 */
public class DetalleVenta  implements java.io.Serializable {


     private int iddetalle;
     private Producto producto;
     private Venta venta;
     private Float cantidad;
     private Float precio;
     private Float totaldetalle;

    public DetalleVenta() {
    }

	
    public DetalleVenta(int iddetalle) {
        this.iddetalle = iddetalle;
    }
    public DetalleVenta(int iddetalle, Producto producto, Venta venta, Float cantidad, Float precio, Float totaldetalle) {
       this.iddetalle = iddetalle;
       this.producto = producto;
       this.venta = venta;
       this.cantidad = cantidad;
       this.precio = precio;
       this.totaldetalle = totaldetalle;
    }
   
    public int getIddetalle() {
        return this.iddetalle;
    }
    
    public void setIddetalle(int iddetalle) {
        this.iddetalle = iddetalle;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public Float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Float cantidad) {
        this.cantidad = cantidad;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public Float getTotaldetalle() {
        return this.totaldetalle;
    }
    
    public void setTotaldetalle(Float totaldetalle) {
        this.totaldetalle = totaldetalle;
    }




}


